runs:
  # agent
  vstar_reward_bench_v8/Qwen2.5-VL-7B-Instruct/agent_image_zoom_in_tool:
    script: eval_utils/common/eval_vllm_api_agent_verl.py
    model: Qwen/Qwen2.5-VL-7B-Instruct
    api_base: http://10.102.198.47:36000/v1
    api_key: EMPTY
    bench_name: vstar_reward_bench_v8
    work_dir: ./eval_results
    workers: 4
    proxy: false
    temperature: 0.0
    max_tokens: 8192
    tool_config_path: /path/to/your/tool_config.yaml
    max_round: 8
    max_tool_response_length: 4096
  # direct
  mmif_rm_all/Qwen2.5-VL-7B-Instruct/direct:
    script: eval_utils/common/eval_vllm_api_direct.py
    model: Qwen/Qwen2.5-VL-7B-Instruct
    api_base: http://10.102.198.47:36000/v1
    api_key: EMPTY
    bench_name: mmif_rm_all
    work_dir: ./eval_results
    workers: 16
    proxy: false
    temperature: 0.0
    max_tokens: 8192